ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE TABLE TEST_USER.EMPLOYEES (
    id          NUMBER PRIMARY KEY,
    fname       VARCHAR2(100),
    hire_date   DATE
);

INSERT INTO TEST_USER.EMPLOYEES VALUES (1, 'Alice', DATE '2024-01-15');
INSERT INTO TEST_USER.EMPLOYEES VALUES (2, 'Bob', DATE '2023-05-08');
INSERT INTO TEST_USER.EMPLOYEES VALUES (3, 'Carol', DATE '2024-10-27');

COMMIT;

EXIT;